// vue-runtime/src/App.vue
<template>
  <div id="app">
    <div class="header">
      <div class="logo"><img src="./assets/logo.jpeg" alt="Confiturator Logo" /></div>
      <div class="subtitle">JavaScript Configurations for Everyone!</div>
      <div class="techlogo"><img src="./assets/vue-logo.png" alt="Vue Logo" /></div>
    </div>
    <div class="content">
      Test Phrase: {{ phrase }}!
    </div>
  </div>
</template>

<script>
export default {
  name: 'App',
  data: function () {
    return {
      phrase: 'Not Configured'
    }
  },
  created () {
    console.log(window.config)
    if (window.config && window.config.TEST_PHRASE !== undefined) {
      this.phrase = window.config.TEST_PHRASE;
    }
  }
}
</script>

<style>
#app {
  font-family: 'Avenir', Helvetica, Arial, sans-serif;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
}

  .header {
    display: flex;
    align-items: center;
    background: #E79115;
    border-bottom: 25px solid #2E2929;
    border-radius: 15px;
  }
  .logo {
    flex: 1;
  }
  .logo img {
    margin-left: 25px;
    margin-top: 10px;
  }
  .techlogo {
    flex: 1;
    text-align: center;
  }
  .techlogo img {
    background: white;
    height: 125px;
    padding: 5px;
    border-radius: 15px;
  }
  .subtitle {
    font-size: 2.5rem;
    vertical-align: middle;
    text-align: center;
    font-weight: 500;
    flex: 3;
  }
  .content {
    text-align: center;
    font-size: 2.0rem;
    padding-top: 25px;
  }
</style>

// react-runtime/src/App.js
import React from 'react';
import logo from './logo.jpeg';
import reactLogo from './logo.svg';

import './App.css';

function App() {
  let testPhrase = 'Not configured';

  if (window.config.TEST_PHRASE !== undefined) {
      testPhrase = window.config.TEST_PHRASE;
  }

  return (
    <div className="App">
      <header className="header">
        <div className="logo"><img src={logo} alt="Configurator Logo" /></div>
        <div className="subtitle">JavaScript Configurations for Everyone!</div>
        <div className="techlogo"><img src={reactLogo} alt="React Logo" /></div>
      </header>
      <div className="content">
        Test Phrase: { testPhrase }!
      </div>
    </div>
  );
}

export default App;
